import type { RaceEvent } from "@/types/content";

export const RACE_EVENTS: RaceEvent[] = [
    {
        "id": "4t-round-1",
        "title": "Campeonato 4T — Ronda 1",
        "category": "Karting 4T",
        "date": "2026-03-08",
        "location": "Autódromo Internacional El Jabalí",
        "time": "8:00 AM",
        "startHour": 8,
        "endHour": 15,
        "page": "/eventos/campeonato-4t"
    },
    {
        "id": "karting-rental-1",
        "title": "Karting Rental Experience",
        "category": "Karting Rental",
        "date": "2026-03-13",
        "location": "Autódromo Internacional El Jabalí",
        "time": "5:00 PM – 12:00 MN",
        "startHour": 17,
        "endHour": 23,
        "page": "/karting/kartingrentalexperience"
    },
    {
        "id": "karting-rental-21",
        "title": "Karting Rental Experience",
        "category": "Karting Rental",
        "date": "2026-03-14",
        "location": "Autódromo Internacional El Jabalí",
        "time": "1:00 PM – 12:00 MN",
        "startHour": 13,
        "endHour": 23,
        "page": "/karting/kartingrentalexperience"
    },
    {
        "id": "karting-rental-2",
        "title": "Karting Rental Experience",
        "category": "Karting Rental",
        "date": "2026-03-27",
        "location": "Autódromo Internacional El Jabalí",
        "time": "5:00 PM – 12:00 MN",
        "startHour": 17,
        "endHour": 23,
        "page": "/karting/kartingrentalexperience"
    },
    {
        "id": "karting-rental-22",
        "title": "Karting Rental Experience",
        "category": "Karting Rental",
        "date": "2026-03-28",
        "location": "Autódromo Internacional El Jabalí",
        "time": "1:00 PM – 12:00 MN",
        "startHour": 13,
        "endHour": 23,
        "page": "/karting/kartingrentalexperience"
    },
    {
        "id": "karting-rental-3",
        "title": "Karting Rental Experience",
        "category": "Karting Rental",
        "date": "2026-04-10",
        "location": "Autódromo Internacional El Jabalí",
        "time": "5:00 PM – 12:00 MN",
        "startHour": 17,
        "endHour": 23,
        "page": "/karting/kartingrentalexperience"
    },
    {
        "id": "karting-rental-23",
        "title": "Karting Rental Experience",
        "category": "Karting Rental",
        "date": "2026-04-11",
        "location": "Autódromo Internacional El Jabalí",
        "time": "1:00 PM – 12:00 MN",
        "startHour": 13,
        "endHour": 23,
        "page": "/karting/kartingrentalexperience"
    },
    {
        "id": "karting-rental-4",
        "title": "Karting Rental Experience",
        "category": "Karting Rental",
        "date": "2026-04-24",
        "location": "Autódromo Internacional El Jabalí",
        "time": "5:00 PM – 12:00 MN",
        "startHour": 17,
        "endHour": 23,
        "page": "/karting/kartingrentalexperience"
    },
    {
        "id": "4t-round-2",
        "title": "Campeonato 4T — Ronda 2",
        "category": "Karting 4T",
        "date": "2026-04-26",
        "location": "Autódromo Internacional El Jabalí",
        "time": "8:00 AM",
        "startHour": 8,
        "endHour": 15,
        "page": "/eventos/campeonato-4t"
    },
    {
        "id": "karting-rental-5",
        "title": "Karting Rental Experience",
        "category": "Karting Rental",
        "date": "2026-05-08",
        "location": "Autódromo Internacional El Jabalí",
        "time": "5:00 PM – 12:00 MN",
        "startHour": 17,
        "endHour": 23,
        "page": "/karting/kartingrentalexperience"
    },
    {
        "id": "karting-rental-24",
        "title": "Karting Rental Experience",
        "category": "Karting Rental",
        "date": "2026-05-09",
        "location": "Autódromo Internacional El Jabalí",
        "time": "1:00 PM – 12:00 MN",
        "startHour": 13,
        "endHour": 23,
        "page": "/karting/kartingrentalexperience"
    },
    {
        "id": "karting-rental-6",
        "title": "Karting Rental Experience",
        "category": "Karting Rental",
        "date": "2026-05-22",
        "location": "Autódromo Internacional El Jabalí",
        "time": "5:00 PM – 12:00 MN",
        "startHour": 17,
        "endHour": 23,
        "page": "/karting/kartingrentalexperience"
    },
    {
        "id": "karting-rental-25",
        "title": "Karting Rental Experience",
        "category": "Karting Rental",
        "date": "2026-05-30",
        "location": "Autódromo Internacional El Jabalí",
        "time": "1:00 PM – 12:00 MN",
        "startHour": 13,
        "endHour": 23,
        "page": "/karting/kartingrentalexperience"
    },
    {
        "id": "4t-round-3",
        "title": "Campeonato 4T — Ronda 3",
        "category": "Karting 4T",
        "date": "2026-06-07",
        "location": "Autódromo Internacional El Jabalí",
        "time": "8:00 AM",
        "startHour": 8,
        "endHour": 15,
        "page": "/eventos/campeonato-4t"
    },
    {
        "id": "karting-rental-7",
        "title": "Karting Rental Experience",
        "category": "Karting Rental",
        "date": "2026-06-12",
        "location": "Autódromo Internacional El Jabalí",
        "time": "5:00 PM – 12:00 MN",
        "startHour": 17,
        "endHour": 23,
        "page": "/karting/kartingrentalexperience"
    },
    {
        "id": "karting-rental-26",
        "title": "Karting Rental Experience",
        "category": "Karting Rental",
        "date": "2026-06-13",
        "location": "Autódromo Internacional El Jabalí",
        "time": "1:00 PM – 12:00 MN",
        "startHour": 13,
        "endHour": 23,
        "page": "/karting/kartingrentalexperience"
    },
    {
        "id": "karting-rental-8",
        "title": "Karting Rental Experience",
        "category": "Karting Rental",
        "date": "2026-06-26",
        "location": "Autódromo Internacional El Jabalí",
        "time": "5:00 PM – 12:00 MN",
        "startHour": 17,
        "endHour": 23,
        "page": "/karting/kartingrentalexperience"
    },
    {
        "id": "karting-rental-27",
        "title": "Karting Rental Experience",
        "category": "Karting Rental",
        "date": "2026-06-27",
        "location": "Autódromo Internacional El Jabalí",
        "time": "1:00 PM – 12:00 MN",
        "startHour": 13,
        "endHour": 23,
        "page": "/karting/kartingrentalexperience"
    },
    {
        "id": "4t-round-4",
        "title": "Campeonato 4T — Ronda 4",
        "category": "Karting 4T",
        "date": "2026-07-05",
        "location": "Autódromo Internacional El Jabalí",
        "time": "8:00 AM",
        "startHour": 8,
        "endHour": 15,
        "page": "/eventos/campeonato-4t"
    },
    {
        "id": "karting-rental-9",
        "title": "Karting Rental Experience",
        "category": "Karting Rental",
        "date": "2026-07-10",
        "location": "Autódromo Internacional El Jabalí",
        "time": "5:00 PM – 12:00 MN",
        "startHour": 17,
        "endHour": 23,
        "page": "/karting/kartingrentalexperience"
    },
    {
        "id": "karting-rental-28",
        "title": "Karting Rental Experience",
        "category": "Karting Rental",
        "date": "2026-07-18",
        "location": "Autódromo Internacional El Jabalí",
        "time": "1:00 PM – 12:00 MN",
        "startHour": 13,
        "endHour": 23,
        "page": "/karting/kartingrentalexperience"
    },
    {
        "id": "karting-rental-10",
        "title": "Karting Rental Experience",
        "category": "Karting Rental",
        "date": "2026-07-24",
        "location": "Autódromo Internacional El Jabalí",
        "time": "5:00 PM – 12:00 MN",
        "startHour": 17,
        "endHour": 23,
        "page": "/karting/kartingrentalexperience"
    },
    {
        "id": "karting-rental-29",
        "title": "Karting Rental Experience",
        "category": "Karting Rental",
        "date": "2026-08-01",
        "location": "Autódromo Internacional El Jabalí",
        "time": "1:00 PM – 12:00 MN",
        "startHour": 13,
        "endHour": 23,
        "page": "/karting/kartingrentalexperience"
    },
    {
        "id": "karting-rental-11",
        "title": "Karting Rental Experience",
        "category": "Karting Rental",
        "date": "2026-08-21",
        "location": "Autódromo Internacional El Jabalí",
        "time": "5:00 PM – 12:00 MN",
        "startHour": 17,
        "endHour": 23,
        "page": "/karting/kartingrentalexperience"
    },
    {
        "id": "karting-rental-30",
        "title": "Karting Rental Experience",
        "category": "Karting Rental",
        "date": "2026-08-22",
        "location": "Autódromo Internacional El Jabalí",
        "time": "1:00 PM – 12:00 MN",
        "startHour": 13,
        "endHour": 23,
        "page": "/karting/kartingrentalexperience"
    },
    {
        "id": "karting-rental-12",
        "title": "Karting Rental Experience",
        "category": "Karting Rental",
        "date": "2026-08-28",
        "location": "Autódromo Internacional El Jabalí",
        "time": "5:00 PM – 12:00 MN",
        "startHour": 17,
        "endHour": 23,
        "page": "/karting/kartingrentalexperience"
    },
    {
        "id": "karting-rental-31",
        "title": "Karting Rental Experience",
        "category": "Karting Rental",
        "date": "2026-09-05",
        "location": "Autódromo Internacional El Jabalí",
        "time": "1:00 PM – 12:00 MN",
        "startHour": 13,
        "endHour": 23,
        "page": "/karting/kartingrentalexperience"
    },
    {
        "id": "karting-rental-13",
        "title": "Karting Rental Experience",
        "category": "Karting Rental",
        "date": "2026-09-11",
        "location": "Autódromo Internacional El Jabalí",
        "time": "5:00 PM – 12:00 MN",
        "startHour": 17,
        "endHour": 23,
        "page": "/karting/kartingrentalexperience"
    },
    {
        "id": "4t-round-5",
        "title": "Campeonato 4T — Ronda 5",
        "category": "Karting 4T",
        "date": "2026-09-13",
        "location": "Autódromo Internacional El Jabalí",
        "time": "8:00 AM",
        "startHour": 8,
        "endHour": 15,
        "page": "/eventos/campeonato-4t"
    },
    {
        "id": "karting-rental-14",
        "title": "Karting Rental Experience",
        "category": "Karting Rental",
        "date": "2026-09-18",
        "location": "Autódromo Internacional El Jabalí",
        "time": "5:00 PM – 12:00 MN",
        "startHour": 17,
        "endHour": 23,
        "page": "/karting/kartingrentalexperience"
    },
    {
        "id": "karting-rental-32",
        "title": "Karting Rental Experience",
        "category": "Karting Rental",
        "date": "2026-09-19",
        "location": "Autódromo Internacional El Jabalí",
        "time": "1:00 PM – 12:00 MN",
        "startHour": 13,
        "endHour": 23,
        "page": "/karting/kartingrentalexperience"
    },
    {
        "id": "karting-rental-33",
        "title": "Karting Rental Experience",
        "category": "Karting Rental",
        "date": "2026-10-03",
        "location": "Autódromo Internacional El Jabalí",
        "time": "1:00 PM – 12:00 MN",
        "startHour": 13,
        "endHour": 23,
        "page": "/karting/kartingrentalexperience"
    },
    {
        "id": "karting-rental-15",
        "title": "Karting Rental Experience",
        "category": "Karting Rental",
        "date": "2026-10-09",
        "location": "Autódromo Internacional El Jabalí",
        "time": "5:00 PM – 12:00 MN",
        "startHour": 17,
        "endHour": 23,
        "page": "/karting/kartingrentalexperience"
    },
    {
        "id": "karting-rental-34",
        "title": "Karting Rental Experience",
        "category": "Karting Rental",
        "date": "2026-10-10",
        "location": "Autódromo Internacional El Jabalí",
        "time": "1:00 PM – 12:00 MN",
        "startHour": 13,
        "endHour": 23,
        "page": "/karting/kartingrentalexperience"
    },
    {
        "id": "karting-rental-16",
        "title": "Karting Rental Experience",
        "category": "Karting Rental",
        "date": "2026-10-23",
        "location": "Autódromo Internacional El Jabalí",
        "time": "5:00 PM – 12:00 MN",
        "startHour": 17,
        "endHour": 23,
        "page": "/karting/kartingrentalexperience"
    },
    {
        "id": "4t-round-6",
        "title": "Campeonato 4T — Ronda 6",
        "category": "Karting 4T",
        "date": "2026-10-25",
        "location": "Autódromo Internacional El Jabalí",
        "time": "8:00 AM",
        "startHour": 8,
        "endHour": 15,
        "page": "/eventos/campeonato-4t"
    },
    {
        "id": "karting-rental-17",
        "title": "Karting Rental Experience",
        "category": "Karting Rental",
        "date": "2026-11-06",
        "location": "Autódromo Internacional El Jabalí",
        "time": "5:00 PM – 12:00 MN",
        "startHour": 17,
        "endHour": 23,
        "page": "/karting/kartingrentalexperience"
    },
    {
        "id": "karting-rental-35",
        "title": "Karting Rental Experience",
        "category": "Karting Rental",
        "date": "2026-11-07",
        "location": "Autódromo Internacional El Jabalí",
        "time": "1:00 PM – 12:00 MN",
        "startHour": 13,
        "endHour": 23,
        "page": "/karting/kartingrentalexperience"
    },
    {
        "id": "karting-rental-36",
        "title": "Karting Rental Experience",
        "category": "Karting Rental",
        "date": "2026-11-21",
        "location": "Autódromo Internacional El Jabalí",
        "time": "1:00 PM – 12:00 MN",
        "startHour": 13,
        "endHour": 23,
        "page": "/karting/kartingrentalexperience"
    },
    {
        "id": "karting-rental-18",
        "title": "Karting Rental Experience",
        "category": "Karting Rental",
        "date": "2026-11-27",
        "location": "Autódromo Internacional El Jabalí",
        "time": "5:00 PM – 12:00 MN",
        "startHour": 17,
        "endHour": 23,
        "page": "/karting/kartingrentalexperience"
    },
    {
        "id": "karting-rental-37",
        "title": "Karting Rental Experience",
        "category": "Karting Rental",
        "date": "2026-12-05",
        "location": "Autódromo Internacional El Jabalí",
        "time": "1:00 PM – 12:00 MN",
        "startHour": 13,
        "endHour": 23,
        "page": "/karting/kartingrentalexperience"
    },
    {
        "id": "karting-rental-19",
        "title": "Karting Rental Experience",
        "category": "Karting Rental",
        "date": "2026-12-11",
        "location": "Autódromo Internacional El Jabalí",
        "time": "5:00 PM – 12:00 MN",
        "startHour": 17,
        "endHour": 23,
        "page": "/karting/kartingrentalexperience"
    },
    {
        "id": "karting-rental-20",
        "title": "Karting Rental Experience",
        "category": "Karting Rental",
        "date": "2026-12-18",
        "location": "Autódromo Internacional El Jabalí",
        "time": "5:00 PM – 12:00 MN",
        "startHour": 17,
        "endHour": 23,
        "page": "/karting/kartingrentalexperience"
    },
    {
        "id": "karting-rental-38",
        "title": "Karting Rental Experience",
        "category": "Karting Rental",
        "date": "2026-12-19",
        "location": "Autódromo Internacional El Jabalí",
        "time": "1:00 PM – 12:00 MN",
        "startHour": 13,
        "endHour": 23,
        "page": "/karting/kartingrentalexperience"
    }
];
